name: Deploy to Hostinger
# Ce script se déclenche à chaque fois que vous faites un "push" sur la branche "main"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync Out folder to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # On prend tout ce qui est DANS ton dossier out local
          local-dir: ./out/
          # Chemin exact vu sur ton FileZilla
          server-dir: /domains/elouatikifreres.com/public_html/
          # On ne supprime pas les fichiers distants pour éviter les erreurs de droits
          dangerous-clean-slate: false
          # Option pour ignorer les erreurs de certificats SSL si besoin
          protocol: ftp
